dist: focal
language: python
python:
- 3.8
- 3.9
- 3.10
- 3.11
- 3.12
cache: pip
jobs:
  fast_finish: true
install:
- pip install -U pip setuptools
- pip install .
- pip install pytest pytest-django pytest-pythonpath wagtail-factories
script:
- pytest
deploy:
  provider: pypi
  server: $PYPI_URL
  user: "__token__"
  password: $PYPI_TOKEN
  skip_existing: true
  on:
    tags: true
